---
apiVersion: batch/v1
kind: Job
metadata:
  namespace: takahe-dev
  name: migrate
spec:
  ttlSecondsAfterFinished: 120
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: webserver
          image: jointakahe/takahe-dev:edge
          args: ["python3", "manage.py", "migrate"]
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: takahe-config
            - secretRef:
                name: takahe-secret
          resources:
            requests:
              memory: "1024Mi"
            limits:
              memory: "1024Mi"
