apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: rss-bridge
  name: rss-bridge
spec:
  rules:
  - host: rss-bridge.shuuji3.xyz
    http:
      paths:
      - backend:
          service:
            name: rss-bridge
            port:
              number: 80
        path: /
        pathType: Prefix
