apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: matrix-pi-k8s-shuuji3-xyz
  namespace: matrix
spec:
  secretName: matrix-pi-k8s-shuuji3-xyz-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: matrix.pi-k8s.shuuji3.xyz
  dnsNames:
  - matrix.pi-k8s.shuuji3.xyz

