---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: takahe-media-pvc
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
